# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://chocolate-drop-motivation.netlify.app"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
